-- Supabase merged restore file
-- Best used on a fresh Supabase project.
-- This restores your public schema objects, public data, and Storage metadata.
-- It does NOT restore the actual binary files inside Storage buckets.

-- ===== roles.sql =====
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
ALTER ROLE "anon" SET "statement_timeout" TO '3s';
ALTER ROLE "authenticated" SET "statement_timeout" TO '8s';
ALTER ROLE "authenticator" SET "statement_timeout" TO '8s';
RESET ALL;

-- ===== schema.sql =====
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;

ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';
SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."cart" (
    "id" bigint NOT NULL,
    "product_id" integer
);
ALTER TABLE "public"."cart" OWNER TO "postgres";
COMMENT ON TABLE "public"."cart" IS 'Cart';
ALTER TABLE "public"."cart" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cart_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."contacts" (
    "id" bigint NOT NULL,
    "name" "text",
    "email" "text",
    "message" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);
ALTER TABLE "public"."contacts" OWNER TO "postgres";
ALTER TABLE "public"."contacts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contacts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" integer NOT NULL,
    "name" "text",
    "price" numeric,
    "image_url" "text",
    "category" "text",
    "discount" smallint
);
ALTER TABLE "public"."products" OWNER TO "postgres";
COMMENT ON COLUMN "public"."products"."discount" IS 'products discount in percentage';

CREATE SEQUENCE IF NOT EXISTS "public"."products_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."products_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."products_id_seq" OWNED BY "public"."products"."id";
ALTER TABLE ONLY "public"."products" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."products_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."cart" ADD CONSTRAINT "cart_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."contacts" ADD CONSTRAINT "contacts_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."products" ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."cart" ADD CONSTRAINT "cart_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id");

CREATE POLICY "Allow Inserts" ON "public"."contacts" FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all" ON "public"."products" USING (true);
CREATE POLICY "Allow all operations" ON "public"."products" USING (true) WITH CHECK (true);
CREATE POLICY "Allow insert" ON "public"."contacts" FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow read access" ON "public"."products" FOR SELECT USING (true);
CREATE POLICY "Delete item from cart" ON "public"."cart" FOR DELETE USING (true);
CREATE POLICY "Enable insert for users based on user_id" ON "public"."cart" FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read access for all users" ON "public"."cart" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."products" FOR SELECT USING (true);

ALTER TABLE "public"."cart" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."contacts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";
GRANT ALL ON TABLE "public"."cart" TO "anon";
GRANT ALL ON TABLE "public"."cart" TO "authenticated";
GRANT ALL ON TABLE "public"."cart" TO "service_role";
GRANT ALL ON SEQUENCE "public"."cart_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cart_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cart_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."contacts" TO "anon";
GRANT ALL ON TABLE "public"."contacts" TO "authenticated";
GRANT ALL ON TABLE "public"."contacts" TO "service_role";
GRANT ALL ON SEQUENCE "public"."contacts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contacts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contacts_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";

-- ===== data.sql converted to standard SQL =====
SET session_replication_role = replica;

INSERT INTO "public"."products" ("id", "name", "price", "image_url", "category", "discount") VALUES
(10, 'Apple Watch Ultra 3', 899.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776827944913-Apple%20Watch%20Ultra%203.png', 'smartwatch', 5),
(7, 'Galaxy Buds4 Pro', 259.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776827959632-Galaxy%20Buds4%20Pro.png', 'headphone', 8),
(1, 'iPhone 17', 899.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776827969904-iPhone%2017.png', 'phone', 20),
(2, 'Galaxy S26', 799.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776827986298-Galaxy%20S26.png', 'phone', 15),
(9, 'Samsung Galaxy Watch 8', 379.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776828006127-Samsung%20Galaxy%20Watch%208.png', 'smartwatch', NULL),
(3, 'MacBook Air', 1199.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776828017361-MacBook%20Air.png', 'laptop', NULL),
(4, 'Galaxy Book6 Pro', 1999.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776828039226-Galaxy%20Book6%20Pro.png', 'laptop', NULL),
(5, 'Galaxy Tab S11 Ultra', 1399.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776828051767-Galaxy%20Tab%20S11%20Ultra.png', 'tablet', NULL),
(6, 'iPad Pro', 1129.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776828063489-iPad%20Pro.png', 'tablet', NULL),
(8, 'AirPods Pro 3', 249.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776828076297-AirPods%20Pro%203.png', 'headphone', NULL),
(12, 'Apple Pencil', 89.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776828087870-Apple%20Pencil.png', 'accessorie', NULL),
(11, '45W Super Fast Charger 2.0', 39.99, 'https://eehtvevnukdhrwudlmat.supabase.co/storage/v1/object/public/product-images/1776828096745-45W%20Super%20Fast%20Charger%202.0.png', 'accessorie', NULL)
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "price" = EXCLUDED."price",
  "image_url" = EXCLUDED."image_url",
  "category" = EXCLUDED."category",
  "discount" = EXCLUDED."discount";

INSERT INTO "public"."contacts" ("id", "name", "email", "message", "created_at") VALUES
(1, 'John Smith', 'JohnSmith1k@gmail.com', 'hi', '2026-04-20 18:50:46.097192'),
(2, 'John varesa', 'JohnVaresa1k@gmail.com', 'I need help', '2026-04-20 18:54:50.145799'),
(3, 'john doe', 'johndoe@gmail.com', 'hi l need some help with my apple watch, do you do supports ', '2026-04-21 13:37:31.470208')
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "email" = EXCLUDED."email",
  "message" = EXCLUDED."message",
  "created_at" = EXCLUDED."created_at";

INSERT INTO "storage"."buckets" ("id", "name", "owner", "created_at", "updated_at", "public", "avif_autodetection", "file_size_limit", "allowed_mime_types", "owner_id", "type") VALUES
('product-images', 'product-images', NULL, '2026-03-30 17:53:50.656385+00', '2026-03-30 17:53:50.656385+00', true, false, NULL, NULL, NULL, 'STANDARD')
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "owner" = EXCLUDED."owner",
  "created_at" = EXCLUDED."created_at",
  "updated_at" = EXCLUDED."updated_at",
  "public" = EXCLUDED."public",
  "avif_autodetection" = EXCLUDED."avif_autodetection",
  "file_size_limit" = EXCLUDED."file_size_limit",
  "allowed_mime_types" = EXCLUDED."allowed_mime_types",
  "owner_id" = EXCLUDED."owner_id",
  "type" = EXCLUDED."type";

INSERT INTO "storage"."objects" ("id", "bucket_id", "name", "owner", "created_at", "updated_at", "last_accessed_at", "metadata", "version", "owner_id", "user_metadata") VALUES
('b512a0fb-ef62-434b-b929-3f2480a210c1', 'product-images', '.emptyFolderPlaceholder', NULL, '2026-03-30 18:07:40.801684+00', '2026-03-30 18:07:40.801684+00', '2026-03-30 18:07:40.801684+00', $json${"eTag": "\"d41d8cd98f00b204e9800998ecf8427e\"", "size": 0, "mimetype": "application/octet-stream", "cacheControl": "max-age=3600", "lastModified": "2026-03-30T18:07:40.797Z", "contentLength": 0, "httpStatusCode": 200}$json$::jsonb, '63c7b6fe-b102-4325-892c-7aec2d84d604', NULL, '{}'::jsonb),
('de280db4-bcf5-42fd-bf0b-ef7ff7d75f8d', 'product-images', '1776827944913-Apple Watch Ultra 3.png', NULL, '2026-04-22 03:19:05.599946+00', '2026-04-22 03:19:05.599946+00', '2026-04-22 03:19:05.599946+00', $json${"eTag": "\"b2e94bc0f8624017a755eaf9624b2bdb\"", "size": 703003, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:19:06.000Z", "contentLength": 703003, "httpStatusCode": 200}$json$::jsonb, '37cd77d3-fcb5-4173-a1b4-130855ea47c8', NULL, '{}'::jsonb),
('1b04403f-ff5d-42b4-be81-e1c129251c9b', 'product-images', '1776827959632-Galaxy Buds4 Pro.png', NULL, '2026-04-22 03:19:19.961901+00', '2026-04-22 03:19:19.961901+00', '2026-04-22 03:19:19.961901+00', $json${"eTag": "\"42b47b7a36e837950fee5f10ee288e5f\"", "size": 683776, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:19:20.000Z", "contentLength": 683776, "httpStatusCode": 200}$json$::jsonb, '3b7433c0-5402-41b5-b2ec-98f0361e48dc', NULL, '{}'::jsonb),
('e2a8808f-8a13-4f14-bb13-3cbedb2bc0f7', 'product-images', '1776827969904-iPhone 17.png', NULL, '2026-04-22 03:19:30.350382+00', '2026-04-22 03:19:30.350382+00', '2026-04-22 03:19:30.350382+00', $json${"eTag": "\"0034a7c7ef9674c0d9ce4754b660da93\"", "size": 695962, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:19:31.000Z", "contentLength": 695962, "httpStatusCode": 200}$json$::jsonb, '9ebb059b-687a-4706-8b70-e1b8d114bc01', NULL, '{}'::jsonb),
('d672b194-9400-4517-a5ea-c3c4ecc45ebc', 'product-images', '1776827986298-Galaxy S26.png', NULL, '2026-04-22 03:19:46.962023+00', '2026-04-22 03:19:46.962023+00', '2026-04-22 03:19:46.962023+00', $json${"eTag": "\"6c3d738b07734f2fbbd6b039867fe68f\"", "size": 753435, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:19:47.000Z", "contentLength": 753435, "httpStatusCode": 200}$json$::jsonb, 'dc17740d-ba11-4025-af7e-065a3156387d', NULL, '{}'::jsonb),
('c094bfe3-44c6-4d49-9c78-f0ef2db5ace2', 'product-images', '1776828006127-Samsung Galaxy Watch 8.png', NULL, '2026-04-22 03:20:06.431972+00', '2026-04-22 03:20:06.431972+00', '2026-04-22 03:20:06.431972+00', $json${"eTag": "\"adc3b8a63e7b8f25b998e79f1c35828c\"", "size": 663790, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:20:07.000Z", "contentLength": 663790, "httpStatusCode": 200}$json$::jsonb, '29eab3a1-5269-4619-b802-5459e2241231', NULL, '{}'::jsonb),
('5606d7b2-3b22-48d3-a5a2-8b4bb42b3cc1', 'product-images', '1776828017361-MacBook Air.png', NULL, '2026-04-22 03:20:18.556858+00', '2026-04-22 03:20:18.556858+00', '2026-04-22 03:20:18.556858+00', $json${"eTag": "\"cafd57775eb97b20c1e63336cd5ef038\"", "size": 736347, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:20:19.000Z", "contentLength": 736347, "httpStatusCode": 200}$json$::jsonb, 'fa1fe9cc-77b1-4df5-bca6-ab6853511acd', NULL, '{}'::jsonb),
('4462a042-28a5-40b8-917d-7e72ad20f990', 'product-images', '1776828051767-Galaxy Tab S11 Ultra.png', NULL, '2026-04-22 03:20:52.158524+00', '2026-04-22 03:20:52.158524+00', '2026-04-22 03:20:52.158524+00', $json${"eTag": "\"cdf0222f8503bb0d650d01f945378592\"", "size": 581800, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:20:53.000Z", "contentLength": 581800, "httpStatusCode": 200}$json$::jsonb, '2841c122-5178-4b22-8336-16e6630d96e3', NULL, '{}'::jsonb),
('ef0f867a-11c7-4318-b31e-85b0e0107391', 'product-images', '1776828063489-iPad Pro.png', NULL, '2026-04-22 03:21:03.927807+00', '2026-04-22 03:21:03.927807+00', '2026-04-22 03:21:03.927807+00', $json${"eTag": "\"00b977c98ba79a8e818f060593f37eb0\"", "size": 803108, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:21:04.000Z", "contentLength": 803108, "httpStatusCode": 200}$json$::jsonb, '71e84520-d606-47ed-9a04-019daea8ee66', NULL, '{}'::jsonb),
('a55f3078-8704-415d-bd96-0929a5dff8e1', 'product-images', '1776828087870-Apple Pencil.png', NULL, '2026-04-22 03:21:28.31463+00', '2026-04-22 03:21:28.31463+00', '2026-04-22 03:21:28.31463+00', $json${"eTag": "\"33a276571d8a7d95579b6844d97b9ea6\"", "size": 63377, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:21:29.000Z", "contentLength": 63377, "httpStatusCode": 200}$json$::jsonb, '1703f0fd-a4a7-409e-99c0-7000b3c6ba4c', NULL, '{}'::jsonb),
('702a806f-4a0f-42dc-90ef-2b304fcec561', 'product-images', '1776828039226-Galaxy Book6 Pro.png', NULL, '2026-04-22 03:20:39.687391+00', '2026-04-22 03:20:39.687391+00', '2026-04-22 03:20:39.687391+00', $json${"eTag": "\"06ada03fee9fb9e209374cbc30f14e17\"", "size": 635085, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:20:40.000Z", "contentLength": 635085, "httpStatusCode": 200}$json$::jsonb, '1cbf7249-023f-4de0-bea3-12a6cb414731', NULL, '{}'::jsonb),
('a611638e-ff28-482d-99df-80c986b2e465', 'product-images', '1776828076297-AirPods Pro 3.png', NULL, '2026-04-22 03:21:16.588597+00', '2026-04-22 03:21:16.588597+00', '2026-04-22 03:21:16.588597+00', $json${"eTag": "\"356a4bf17c8fa1eee303011b346e9602\"", "size": 528355, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:21:17.000Z", "contentLength": 528355, "httpStatusCode": 200}$json$::jsonb, '1962c98b-865e-44af-942c-3abc16fc9243', NULL, '{}'::jsonb),
('c97f7e17-9f45-49b5-9ecc-c0563e6d4e83', 'product-images', '1776828096745-45W Super Fast Charger 2.0.png', NULL, '2026-04-22 03:21:37.395599+00', '2026-04-22 03:21:37.395599+00', '2026-04-22 03:21:37.395599+00', $json${"eTag": "\"9ba2d8e794092a70e545f9256688f2d5\"", "size": 863672, "mimetype": "image/png", "cacheControl": "max-age=3600", "lastModified": "2026-04-22T03:21:38.000Z", "contentLength": 863672, "httpStatusCode": 200}$json$::jsonb, '5b300d94-c602-4ea0-9bb1-ed37f964b468', NULL, '{}'::jsonb)
ON CONFLICT ("id") DO UPDATE SET
  "bucket_id" = EXCLUDED."bucket_id",
  "name" = EXCLUDED."name",
  "owner" = EXCLUDED."owner",
  "created_at" = EXCLUDED."created_at",
  "updated_at" = EXCLUDED."updated_at",
  "last_accessed_at" = EXCLUDED."last_accessed_at",
  "metadata" = EXCLUDED."metadata",
  "version" = EXCLUDED."version",
  "owner_id" = EXCLUDED."owner_id",
  "user_metadata" = EXCLUDED."user_metadata";

SELECT pg_catalog.setval('"auth"."refresh_tokens_id_seq"', 1, false);
SELECT pg_catalog.setval('"public"."cart_id_seq"', 26, true);
SELECT pg_catalog.setval('"public"."contacts_id_seq"', 3, true);
SELECT pg_catalog.setval('"public"."products_id_seq"', 33, true);

RESET ALL;
SET session_replication_role = DEFAULT;
